export const ACTIVE_QUERY = "ACTIVE_QUERY_ADD_CAR";
export const QUERY_SUCCESS = "QUERY_SUCCESS_ADD_CAR";
export const QUERY_FAILURE = "QUERY_FAILURE_ADD_CAR";
export const POST_QUERY = "POST_QUERY_ADD_CAR";
export const CHANGE_MODEL = "CHANGE_MODEL_ADD_CAR";
export const CHANGE_COLOR = "CHANGE_COLOR_ADD_CAR";
export const CHANGE_PRICE = "CHANGE_PRICE_ADD_CAR";
export const CHANGE_YEAR = "CHANGE_YEAR_ADD_CAR";


