export const START_LOADING = "START_LOADING";
export const LOADING_SUCCESS = "LOADING_SUCCESS";
export const LOADING_FAILURE = "LOADING_FAILURE";
export const BUYING_CAR_SUCCESS = "BUYING_CAR_SUCCESS";
export const BUYING_CAR_FAILD = "BUYING_CAR_FAILD";
export const POST_QUERY = "POST_QUERY_BUY_CAR";