export const ACTIVE_QUERY = "ACTIVE_QUERY";
export const QUERY_SUCCESS = "QUERY_SUCCESS";
export const QUERY_FAILURE = "QUERY_FAILURE";
export const CHANGE_PASSWORDS = "CHANGE_PASSWORDS";
export const CHANGE_USERNAME = "CHANGE_USERNAME";
export const CHANGE_PASSWORDS_FAILURE = "CHANGE_PASSWORDS_FAILURE";
export const POST_QUERY = "POST_QUERY";





